version: 2.1

base: &base
  docker:
    - image: circleci/node:8

orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  install_dependencies:
    <<: *base
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths: node_modules

  eslint:
    <<: *base
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Test
          command: npm run lint

  build:
    <<: *base
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Install npm
          command: npm run build-static
      - persist_to_workspace:
          root: ~/project
          paths: static

  deploy:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - aws-s3/sync:
          from: static
          to: 's3://invoices.blackglobe.cz'
					aws-region: eu-central-1
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - install_dependencies
      - eslint:
          requires:
            - install_dependencies
      - build:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - install_dependencies
            - eslint
            - build
          filters:
            branches:
              only:
                - master